# Generated by Django 4.1.4 on 2022-12-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafoliopersonal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=400)),
                ('project_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=450)),
            ],
        ),
    ]
